---
# General server tasks

- name: Create mail user
  user:
    name: vmail
    home: /var/vmail
    shell: /usr/sbin/nologin

- name: Create mail user sieve directory
  file:
    path: /var/vmail/sieve/global
    state: directory
    owner: vmail
    group: vmail
    mode: 0770

- name: Create mail user mailbox directory
  file:
    path: /var/vmail/mailboxes
    state: directory
    owner: vmail
    group: vmail
    mode: 0770

- name: Update
  apt:
    update_cache: yes

- name: Upgrade
  apt:
    upgrade: safe

- name: Install base dependencies
  apt:
    pkg:
      - apt-transport-https
      - ca-certificates
      - gpg
      - gnupg-agent
      - software-properties-common
    state: latest

- name: Set hostname
  hostname:
    name: "{{ host }}"

- name: Add hostname to /etc/hosts
  lineinfile:
    dest: /etc/hosts
    regexp: "^127.0.1.1"
    line: "127.0.1.1 {{ mail_fqdn }} {{ host }}"
    state: present

- name: Set mailname
  copy:
    dest: "/etc/mailname"
    content: "{{ mail_fqdn }}"

- name: Restart systemd-logind
  service:
    name: systemd-logind
    state: restarted

- name: add PasswordAuthentication no to sshd_config line
  lineinfile: dest=/etc/ssh/sshd_config regexp=PasswordAuthentication.* line="PasswordAuthentication no"
  notify: restart sshd

