---
# Group vars for all hosts

host: mail
domain: my.mail.server
ip_address: "{{ ansible_default_ipv4.address }}"
mail_fqdn: "{{ host }}.{{ domain }}"
smtp_fqdn: "smtp.{{ domain }}"
imap_fqdn: "imap.{{ domain }}"
mail_user: mail
email_for_updates: "{{ mail_user }}@{{ domain }}"
