---
# Install Fail2Ban
#

- name: Install package fail2ban
  apt: 
    pkg:
      - fail2ban
    state: latest

- name:
  ansible.builtin.service:
    name: fail2ban
    state: started
    enabled: true
